openapi: 3.0.1
info:
  title: transport-app-admin
  version: '1.0'
servers:
  - url: /Prod
paths:
  /tenants/new:
    post:
      summary: Crea a un usuario
      description: "Con este endpoint se crea un usuario"
      responses:
        "200":
          description: Usuario creado exitosamente
        "400":
          description: Bad request
        "500":
          description: Server Error
      x-amazon-apigateway-integration:
        type: aws_proxy
        credentials:
          Fn::GetAtt:
            - ApiGwExecutionRole
            - Arn
        httpMethod: POST
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateTenant}/invocations
        passthroughBehavior: when_no_match
components: {}
