openapi: 3.0.1
info:
  title: transport-app-admin
  version: '1.0'
servers:
  - url: /Prod
paths:
  /tenants/new:
    post:
      summary: Crea a un tenant
      description: "Con este endpoint se crea un tenant"
      x-amazon-apigateway-integration:
        type: aws
        credentials:
          Fn::GetAtt:
            - ApiGwExecutionRole
            - Arn
        httpMethod: POST
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateTenant}/invocations
        passthroughBehavior: when_no_match
components: {}
