AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  EndPoint Masters

  En este template se crean todos los maestros de la aplicación de transportes

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs16.x

Resources:
  CreateTenant:
    Type: AWS::Serverless::Function
    Properties:
      Description: Función para crear tenant
      CodeUri: ./
      Handler: create-tenant.lambdaHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TenantsTable
      Environment:
        Variables:
          TENANTS_TABLE: !Ref TenantsTable


  TenantsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "TenantsTable"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "tenant"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "tenant"
          KeyType: "HASH"


Outputs:
  CreateTenant:
    Description: "CreateTenant Lambda Function ARN"
    Value: !GetAtt CreateTenant.Arn